# Generated by Django 3.1.7 on 2023-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230928_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCosmeticF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=38, unique=True, verbose_name='Cosmetique femme')),
                ('slug', models.SlugField(blank=True, max_length=38, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
                ('promo_date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cosmetique femme',
            },
        ),
        migrations.CreateModel(
            name='ProductCosmeticH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=38, unique=True, verbose_name='Cosmetique homme')),
                ('slug', models.SlugField(blank=True, max_length=38, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
                ('promo_date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cosmetique homme',
            },
        ),
        migrations.CreateModel(
            name='ProductFish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=38, unique=True, verbose_name='Poisson')),
                ('slug', models.SlugField(blank=True, max_length=38, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
                ('promo_date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Poisson',
            },
        ),
        migrations.CreateModel(
            name='ProductFruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=38, unique=True, verbose_name='Fruit')),
                ('slug', models.SlugField(blank=True, max_length=38, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
                ('promo_date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fruit',
            },
        ),
        migrations.CreateModel(
            name='ProductVegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=38, unique=True, verbose_name='Légume')),
                ('slug', models.SlugField(blank=True, max_length=38, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
                ('promo_date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Légumes',
            },
        ),
    ]
