# Generated by Django 3.1.7 on 2023-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productcosmeticf_productcosmetich_productfish_productfruit_productvegetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvegetable',
            options={'verbose_name': 'Légume'},
        ),
        migrations.AddField(
            model_name='productmeat',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Produit en promotion'),
        ),
    ]
