# Generated by Django 3.1.7 on 2023-09-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230929_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeat',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Image produit'),
        ),
    ]
