# Generated by Django 3.1.7 on 2023-09-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230929_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcosmeticf',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='Pourcentage promotion'),
        ),
        migrations.AddField(
            model_name='productcosmeticf',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Produit en promotion'),
        ),
        migrations.AddField(
            model_name='productcosmetich',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='Pourcentage promotion'),
        ),
        migrations.AddField(
            model_name='productcosmetich',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Produit en promotion'),
        ),
        migrations.AddField(
            model_name='productfish',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='Pourcentage promotion'),
        ),
        migrations.AddField(
            model_name='productfish',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Produit en promotion'),
        ),
        migrations.AddField(
            model_name='productfruit',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='Pourcentage promotion'),
        ),
        migrations.AddField(
            model_name='productfruit',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Produit en promotion'),
        ),
        migrations.AddField(
            model_name='productvegetable',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='Pourcentage promotion'),
        ),
        migrations.AddField(
            model_name='productvegetable',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Produit en promotion'),
        ),
        migrations.AlterField(
            model_name='productcosmeticf',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='productcosmeticf',
            name='promo_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin de promotion'),
        ),
        migrations.AlterField(
            model_name='productcosmeticf',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Image produit'),
        ),
        migrations.AlterField(
            model_name='productcosmeticf',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Viande'),
        ),
        migrations.AlterField(
            model_name='productcosmetich',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='productcosmetich',
            name='promo_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin de promotion'),
        ),
        migrations.AlterField(
            model_name='productcosmetich',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Image produit'),
        ),
        migrations.AlterField(
            model_name='productcosmetich',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Viande'),
        ),
        migrations.AlterField(
            model_name='productfish',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='productfish',
            name='promo_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin de promotion'),
        ),
        migrations.AlterField(
            model_name='productfish',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Image produit'),
        ),
        migrations.AlterField(
            model_name='productfish',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Viande'),
        ),
        migrations.AlterField(
            model_name='productfruit',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='productfruit',
            name='promo_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin de promotion'),
        ),
        migrations.AlterField(
            model_name='productfruit',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Image produit'),
        ),
        migrations.AlterField(
            model_name='productfruit',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Viande'),
        ),
        migrations.AlterField(
            model_name='productvegetable',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='productvegetable',
            name='promo_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin de promotion'),
        ),
        migrations.AlterField(
            model_name='productvegetable',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Image produit'),
        ),
        migrations.AlterField(
            model_name='productvegetable',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Viande'),
        ),
    ]
