# Generated by Django 3.1.7 on 2023-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230929_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcosmeticf',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Cosmetique Femme'),
        ),
        migrations.AlterField(
            model_name='productcosmetich',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Cosmetique Homme'),
        ),
        migrations.AlterField(
            model_name='productfish',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Poisson'),
        ),
        migrations.AlterField(
            model_name='productfruit',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Fruit'),
        ),
        migrations.AlterField(
            model_name='productvegetable',
            name='title',
            field=models.CharField(max_length=38, unique=True, verbose_name='Légume'),
        ),
    ]
