# Generated by Django 4.2.6 on 2023-10-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230929_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcosmeticf',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productcosmetich',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productfish',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productfruit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productmeat',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productvegetable',
            name='slug',
        ),
        migrations.AddField(
            model_name='productmeat',
            name='promo_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date début de promotion'),
        ),
        migrations.AlterField(
            model_name='productmeat',
            name='thumbnail',
            field=models.ImageField(upload_to='products', verbose_name='Image produit'),
        ),
    ]
